development:
  adapter: postgresql
  encoding: utf8
  database: product
  username: flock
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: product_test
  username: flock
  password:
  host: localhost
